# device-plugin.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: micro-device-plugin
  namespace: kube-system
  labels:
    app: micro-device-plugin
spec:
  selector:
    matchLabels:
      app: micro-device-plugin
  template:
    metadata:
      labels:
        app: micro-device-plugin
    spec:
      hostNetwork: true
      tolerations:
        - key: nvidia.com/customgpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: plugin
          image: benyuereal/micro-device-plugin:v1.0.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
            - name: nvidia
              mountPath: /usr/local/nvidia
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: DirectoryOrCreate
        - name: dev
          hostPath:
            path: /dev
        - name: nvidia
          hostPath:
            path: /usr/local/nvidia